import '../models/partner_driver.dart';
import '../models/partner_notification.dart';
import '../models/partner_order.dart';
import '../models/partner_transaction.dart';

class PartnerDummyData {
  static const demoUsername = 'mitra';
  static const demoPassword = '123456';

  static const driver = PartnerDriver(
    id: 'driver_001',
    name: 'Andi Saputra',
    email: 'andi.saputra@mitraantri.com',
    phone: '081298765432',
    rating: 4.9,
    vehicleType: 'Honda Beat',
    vehiclePlate: 'B 1234 XYZ',
    balance: 850000,
    todayIncome: 175000,
    weeklyIncome: 920000,
    monthlyIncome: 3450000,
    completedOrders: 342,
    todayOrders: 7,
    cancelledOrders: 4,
    acceptanceRate: 96.5,
  );

  static List<PartnerOrder> incomingOrders() {
    return [
      PartnerOrder(
        id: 'inc_001',
        customerName: 'Budi Santoso',
        customerPhone: '628111111111',
        category: PartnerServiceCategory.hospital,
        serviceType: 'Hospital Queue',
        destination: 'RS Cipto Mangunkusumo',
        address: 'Jl. Diponegoro No. 71, Senen, Jakarta Pusat',
        distanceKm: 2.1,
        estimatedMinutes: 8,
        price: 45000,
        status: PartnerOrderStatus.waiting,
        date: DateTime(2026, 6, 30, 9, 15),
        isIncoming: true,
      ),
      PartnerOrder(
        id: 'inc_002',
        customerName: 'Siti Rahma',
        customerPhone: '628122222222',
        category: PartnerServiceCategory.fashion,
        serviceType: 'Fashion',
        destination: 'Grand Indonesia',
        address: 'Jl. M.H. Thamrin No. 1, Jakarta Pusat',
        distanceKm: 1.2,
        estimatedMinutes: 5,
        price: 30000,
        status: PartnerOrderStatus.waiting,
        date: DateTime(2026, 6, 30, 9, 22),
        isIncoming: true,
      ),
      PartnerOrder(
        id: 'inc_003',
        customerName: 'Andi Wijaya',
        customerPhone: '628133333333',
        category: PartnerServiceCategory.culinary,
        serviceType: 'Food Delivery',
        destination: 'Warung Padang Sederhana',
        address: 'Jl. Sudirman No. 45, Jakarta Pusat',
        distanceKm: 3.5,
        estimatedMinutes: 12,
        price: 28000,
        status: PartnerOrderStatus.waiting,
        date: DateTime(2026, 6, 30, 9, 30),
        isIncoming: true,
      ),
      PartnerOrder(
        id: 'inc_004',
        customerName: 'Rina Putri',
        customerPhone: '628144444444',
        category: PartnerServiceCategory.publicService,
        serviceType: 'Public Service',
        destination: 'Kantor Samsat',
        address: 'Jl. Raya Pasar Minggu KM 18, Jakarta Selatan',
        distanceKm: 4.8,
        estimatedMinutes: 16,
        price: 55000,
        status: PartnerOrderStatus.waiting,
        date: DateTime(2026, 6, 30, 9, 35),
        isIncoming: true,
      ),
      PartnerOrder(
        id: 'inc_005',
        customerName: 'Kevin',
        customerPhone: '628155555555',
        category: PartnerServiceCategory.event,
        serviceType: 'Event Ticket',
        destination: 'JIExpo Kemayoran',
        address: 'Jl. Benyamin Sueb, Kemayoran, Jakarta Pusat',
        distanceKm: 6.1,
        estimatedMinutes: 20,
        price: 75000,
        status: PartnerOrderStatus.waiting,
        date: DateTime(2026, 6, 30, 9, 40),
        isIncoming: true,
      ),
    ];
  }

  static final orderHistory = <PartnerOrder>[
    PartnerOrder(
      id: 'hist_001',
      customerName: 'Dewi Lestari',
      customerPhone: '628166666666',
      category: PartnerServiceCategory.hospital,
      serviceType: 'Hospital Queue',
      destination: 'RS Fatmawati',
      address: 'Jl. RS Fatmawati Raya, Jakarta Selatan',
      distanceKm: 3.2,
      estimatedMinutes: 10,
      price: 50000,
      status: PartnerOrderStatus.completed,
      date: DateTime(2026, 6, 30, 7, 30),
    ),
    PartnerOrder(
      id: 'hist_002',
      customerName: 'Rizky Pratama',
      customerPhone: '628177777777',
      category: PartnerServiceCategory.culinary,
      serviceType: 'Food Delivery',
      destination: 'McDonald Sudirman',
      address: 'Jl. Jenderal Sudirman, Jakarta Pusat',
      distanceKm: 2.0,
      estimatedMinutes: 7,
      price: 25000,
      status: PartnerOrderStatus.finished,
      date: DateTime(2026, 6, 29, 18, 45),
    ),
    PartnerOrder(
      id: 'hist_003',
      customerName: 'Maya Sari',
      customerPhone: '628188888888',
      category: PartnerServiceCategory.fashion,
      serviceType: 'Fashion',
      destination: 'Senayan City',
      address: 'Jl. Asia Afrika No. 8, Jakarta Selatan',
      distanceKm: 4.1,
      estimatedMinutes: 14,
      price: 35000,
      status: PartnerOrderStatus.accepted,
      date: DateTime(2026, 6, 29, 14, 20),
    ),
    PartnerOrder(
      id: 'hist_004',
      customerName: 'Agus Setiawan',
      customerPhone: '628199999999',
      category: PartnerServiceCategory.publicService,
      serviceType: 'Public Service',
      destination: 'Kantor BPJS',
      address: 'Jl. Letjen Suprapto Kav. 69, Jakarta Pusat',
      distanceKm: 5.5,
      estimatedMinutes: 18,
      price: 60000,
      status: PartnerOrderStatus.cancelled,
      date: DateTime(2026, 6, 28, 11, 0),
    ),
    PartnerOrder(
      id: 'hist_005',
      customerName: 'Linda Wijaya',
      customerPhone: '628100000001',
      category: PartnerServiceCategory.event,
      serviceType: 'Event Ticket',
      destination: 'Gelora Bung Karno',
      address: 'Jl. Pintu Satu Senayan, Jakarta Pusat',
      distanceKm: 3.8,
      estimatedMinutes: 13,
      price: 80000,
      status: PartnerOrderStatus.waiting,
      date: DateTime(2026, 6, 28, 8, 30),
    ),
  ];

  static final notifications = <PartnerNotification>[
    PartnerNotification(
      id: 'notif_001',
      type: PartnerNotificationType.newOrder,
      message: 'Pesanan baru dari Budi Santoso - Hospital Queue',
      timestamp: DateTime(2026, 6, 30, 9, 15),
    ),
    PartnerNotification(
      id: 'notif_002',
      type: PartnerNotificationType.customerCancelled,
      message: 'Agus Setiawan membatalkan pesanan Public Service',
      timestamp: DateTime(2026, 6, 28, 11, 5),
      isRead: true,
    ),
    PartnerNotification(
      id: 'notif_003',
      type: PartnerNotificationType.orderCompleted,
      message: 'Pesanan Dewi Lestari telah selesai',
      timestamp: DateTime(2026, 6, 30, 8, 15),
      isRead: true,
    ),
    PartnerNotification(
      id: 'notif_004',
      type: PartnerNotificationType.paymentReceived,
      message: 'Pembayaran Rp 50.000 diterima ke dompet Anda',
      timestamp: DateTime(2026, 6, 30, 8, 20),
    ),
  ];

  static final transactions = <PartnerTransaction>[
    PartnerTransaction(
      id: 'tx_p_001',
      title: 'Pendapatan Pesanan - Dewi Lestari',
      amount: 50000,
      isCredit: true,
      timestamp: DateTime(2026, 6, 30, 8, 20),
    ),
    PartnerTransaction(
      id: 'tx_p_002',
      title: 'Pendapatan Pesanan - Rizky Pratama',
      amount: 25000,
      isCredit: true,
      timestamp: DateTime(2026, 6, 29, 19, 0),
    ),
    PartnerTransaction(
      id: 'tx_p_003',
      title: 'Penarikan Dana',
      amount: 200000,
      isCredit: false,
      timestamp: DateTime(2026, 6, 28, 16, 30),
    ),
    PartnerTransaction(
      id: 'tx_p_004',
      title: 'Pendapatan Pesanan - Maya Sari',
      amount: 35000,
      isCredit: true,
      timestamp: DateTime(2026, 6, 29, 15, 10),
    ),
    PartnerTransaction(
      id: 'tx_p_005',
      title: 'Bonus Performa Mingguan',
      amount: 75000,
      isCredit: true,
      timestamp: DateTime(2026, 6, 27, 10, 0),
    ),
  ];
}
